In [2]:
import numpy as np

#### 1. Как найти размер памяти занимаемый вектором

In [ ]:
a = np.array([1, 2, 3, 4])
print(a.size * a.itemsize)

#### 2. Создайте вектор со значениями от 1995 до 2025

In [ ]:
a = np.arange(1995, 2026)
print(a)

#### 3. Инвертировать вектор (первый элемент становится последним)

In [ ]:
a = np.array([1, 2, 3, 4])
a = a[::-1]
print(a)

#### 4. Создайте матрицу 3x3 со значениями от 0 до 8


In [ ]:
a = np.arange(0, 9).reshape(3, 3)
print(a)

#### 5. Найдите индексы ненулевых элементов из вектора

In [153]:
a = np.array([1, 2, 3, 4])
print(np.nonzero(a)[0])

[0 1 2 3]


#### 6. Создайте массив 3 на 3 на 3 со случайными значениями

In [ ]:
a = np.random.random((3, 3, 3))
print(a)

#### 7. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения

In [ ]:
a = np.random.random((10, 10))
print(a)
print(f'min = {a.min()}; max = {a.max()}')

#### 8. Создайте случайный вектор размером 100 и найдите среднее значение

In [68]:
a = np.random.random(100)
print(a.mean())

0.5122381518010216


#### 9. Создайте двумерный-массив с 1(единицами) на границе и 0(нулями) внутри

In [ ]:
a = np.ones((10, 10), dtype=np.int64)
a[1:len(a) - 1, 1:len(a) - 1] = 0
print(a)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

#### 10. Создайте матрицу 8x8 и залейте ее шахматным узором

[1., 0., 1., 0., 1., 0., 1., 0.],

[0., 1., 0., 1., 0., 1., 0., 1.],

[1., 0., 1., 0., 1., 0., 1., 0.],

[0., 1., 0., 1., 0., 1., 0., 1.],

[1., 0., 1., 0., 1., 0., 1., 0.],

[0., 1., 0., 1., 0., 1., 0., 1.],

[1., 0., 1., 0., 1., 0., 1., 0.],

[0., 1., 0., 1., 0., 1., 0., 1.]

In [69]:
a = np.ones((8, 8), dtype=np.int64)
a[::2, 1::2] = 0
a[1::2, ::2] = 0
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 11. Рассмотрим массив формы (5,6), каков индекс (x, y) 10-го элемента?

In [82]:
a = np.random.random((5, 6))
x, y = np.unravel_index(9, a.shape)
print(f'({x}, {y})')

(1, 3)


#### 12. Рассмотрим массив размеров (6,7,8), каков индекс (x, y, z) 100-го элемента?

In [83]:
a = np.random.random((6, 7, 8))
x, y, z = np.unravel_index(99, a.shape)
print(f'({x}, {y}, {z})')

(1, 5, 3)


#### 13. Умножьте матрицу 5x3 на матрицу 3x2 (матричное произведение)

In [85]:
a = np.arange(1, 16).reshape((5, 3))
b = np.arange(1, 7).reshape((3, 2))
print(a @ b)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 14. Задан одномерный массив, инвертируйте (поменяйте знак) у всех элементов массива, которые находятся в диапазоне от 3 до 8, прямо в нем самом.

In [88]:
a = np.arange(1, 12)
a[3:9] *= -1
print(a)

[ 1  2  3 -4 -5 -6 -7 -8 -9 10 11]


#### 15. Каковы результаты следующих выражений?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int)
np.array([np.nan]).astype(int).astype(float)
np.array([np.nan]).astype(float)
```

In [90]:
np.array(0) / np.array(0)

/tmp/ipykernel_14145/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [91]:
np.array(0) // np.array(0)

/tmp/ipykernel_14145/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [92]:
np.array([np.nan]).astype(int)

/tmp/ipykernel_14145/3091100680.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int)


array([-9223372036854775808])

In [93]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_14145/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [94]:
np.array([np.nan]).astype(float)

array([nan])

#### 16. Округлить массив с плавающей запятой?  

In [100]:
a = np.random.random((5, 5))
print(a)
a = np.round(a).astype(int)
print(a)

[[0.78310063 0.96564674 0.63778106 0.73720128 0.57237777]
 [0.29851752 0.1601369  0.58523519 0.94492828 0.81405416]
 [0.08770592 0.26921448 0.38762839 0.74646578 0.42889265]
 [0.61286193 0.34710953 0.0229784  0.79593152 0.87491017]
 [0.85487752 0.97270061 0.62888338 0.1296894  0.52182507]]
[[1 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 0]
 [1 0 0 1 1]
 [1 1 1 0 1]]


#### 17. Как найти общие значения между двумя массивами

In [119]:
a = np.arange(1, 10).reshape((3, 3))
b = np.arange(5, 14).reshape((3, 3))
print(a)
print(b)
print(a[np.isin(a, b)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[5 6 7 8 9]


#### 18. Как вычислить корень из отрицательного числа?

In [127]:
print(np.emath.sqrt(-1))

1j


#### 19. Создайте случайный вектор размером 10 и отсортируйте его

In [136]:
a = np.random.random(10)
a.sort()
print(a)

[0.1474712  0.17207047 0.24421651 0.27954042 0.29353872 0.47878411
 0.61692426 0.71553038 0.78571266 0.90941708]


#### 20. Создайте случайную матрицу размером 10 на 10 найдите максимуму по строкам и столбцам по отдельности

In [138]:
a = np.random.random((10, 10))
print(a.max(axis=1))
print(a.max(axis=0))

[0.83353228 0.88831409 0.97504062 0.99556763 0.9922792  0.98234718
 0.89335799 0.64839136 0.97630048 0.98979358]
[0.96796729 0.75099902 0.97630048 0.77974125 0.99556763 0.97504062
 0.90643053 0.98979358 0.9922792  0.98234718]


#### 21. Рассмотрим два случайных массива A и B, проверьте, равны ли они

In [140]:
a = np.random.random((5, 5))
b = np.random.random((5, 5))
print(np.array_equal(a, b))

False


#### 22. Создайте случайный вектор размером 10 и замените все максимальные значения на 0

In [152]:
a = np.random.random(10)
a[a == a.max()] = 0
print(a)

[0.45929859 0.29283488 0.47517121 0.16386521 0.40253665 0.51621842
 0.         0.59876201 0.44250879 0.19989558]


#### 23. Создайте случайный вектор размером 10 и найдите индексы всех минимальных элементов

In [155]:
a = np.random.random(10)
print(a)
print(np.where(a == a.min())[0])

[0.23908451 0.22018902 0.98373184 0.18207451 0.42731271 0.50201931
 0.23193013 0.32736258 0.62579274 0.98875785]
[3]


#### 24.Для двух массивов, X и Y, построить матрицу Коши C (Cij = 1 / (xi - yj))

In [158]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
print(c)

[[-24.03097377  -6.93443063  -3.0678515    3.17156396   3.41832807]
 [ -2.3741195   -4.88047185 -83.26921159 215.35238516  25.58351809]
 [  5.66613848  11.20869888   1.50947924  -1.17320702  12.37435854]
 [  1.41915354   2.19292625  -2.81349264 -29.37109669   1.83064236]
 [ -1.13646413   2.20134891  -2.39782245  -9.13940668  -2.43995271]]


#### 25. Как найти ближайшее значение (к заданному(числу)) в векторе?

In [ ]:
a = np.random.random(10)
print(a)
print(a[np.argmin(np.abs(a - 1))])

[0.827148   0.74858145 0.18433024 0.46656972 0.06430316 0.61436618
 0.67296911 0.32669424 0.4589288  0.74487657]
0.8271479983623192


#### 26. Вычтите среднее значение каждой строки матрицы.  Необходимо вычислить среднее значение каждой строки матрицы и вычесть его из элементов соответствующей строки  

In [170]:
a = np.random.random((10, 10))
print(a - a.mean(axis=1).reshape(10, 1))

[[-0.45147734 -0.308213    0.21981568 -0.36164865 -0.47697728  0.0915057
   0.28769183  0.42472497  0.1559325   0.4186456 ]
 [-0.28113735  0.17608532 -0.49976539  0.38582452  0.14677834 -0.3343188
  -0.24929598  0.39417773  0.14239275  0.11925886]
 [ 0.36090161 -0.3569166   0.38793726 -0.06785218  0.28379201 -0.09112612
   0.20742305 -0.14149186 -0.25079145 -0.33187572]
 [-0.432573    0.29374056  0.16418952  0.26836279 -0.36560817  0.19579943
   0.01229263 -0.35722877  0.21667053  0.00435449]
 [-0.22715559 -0.00534117 -0.30011605  0.28712486 -0.10857138  0.36899525
   0.02656232  0.10683901  0.27019665 -0.4185339 ]
 [ 0.30458211 -0.46483358 -0.19755708 -0.07580205  0.02882489  0.20751334
   0.35852576  0.02233829  0.3088905  -0.49248216]
 [ 0.26158681 -0.52481272 -0.14684213  0.17716313  0.26978887  0.12179436
   0.32221419 -0.46607891 -0.11786829  0.10305468]
 [-0.20715795 -0.17032733  0.08940269 -0.34661392  0.37936425  0.27856527
  -0.33487236  0.2207381  -0.11554614  0.20644739]
 [

#### 27. Отсортировать двумерную матрицу по n-му столбцу?

In [181]:
a = np.random.random((4, 4))
print(a)
a = a[np.argsort(a[:, 2])]
print(a)

[[0.68360261 0.54777414 0.45545829 0.40365851]
 [0.55622524 0.19797268 0.10926438 0.22107792]
 [0.826362   0.11083389 0.74031083 0.48057926]
 [0.08650603 0.82327438 0.84310439 0.65645653]]
[[0.55622524 0.19797268 0.10926438 0.22107792]
 [0.68360261 0.54777414 0.45545829 0.40365851]
 [0.826362   0.11083389 0.74031083 0.48057926]
 [0.08650603 0.82327438 0.84310439 0.65645653]]


#### 28. Определить, есть ли в данной двумерной матрицы нулевые столбцы? Как найти индексы нулевых столбцов в матрице?

In [ ]:
a = np.array([[0, 0, 1],
              [0, 0, 1]])
print(np.where(np.all(a == 0, axis=0))[0])

[0 1]


#### 29. Как найти наиболее часто встречающееся значение в массиве

In [ ]:
a = np.array([[1, 2, 3],
              [1, 2, 2]])
u, c = np.unique(a, return_counts=True)
print(u[np.argmax(c)])

[[1 2 3]
 [1 2 2]]
2
